ORDER_STATUS = {
    "NO_ARTWORK": "no_artwork",
    "PENDING": "pending",
    "PROCESSING": "processing",
    "IN_PRODUCTION": "in_production",
    "ON_HOLD": "on_hold",
    "PRODUCED": "produced",
    "PARTIALLY_PRODUCED": "partially_produced",
    "PACKAGED": "packaged",
    "LABELED": "labeled",
    "READY_FOR_DELIVERY": "ready_for_delivery",
    "PRE_TRANSIT": "pre_transit",
    "IN_TRANSIT": "in_transit",
    "PARTIALLY_DELIVERED": "partially_delivered",
    "DELIVERED": "delivered",
    "DONE": "done",
    "CANCELLED": "cancelled",
    "REFUNDED": "refunded",
    "RETURNED": "returned",
    "ARTWORK_ERROR": "artwork_error",
}
