services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq-custom
    ports:
      - "5672:5672"  # RabbitMQ AMQP protocol port
      - "15672:15672"  # RabbitMQ Management Web UI port
    volumes:
      - ./create_queues.sh:/create_queues.sh  # Mount script vào container
    entrypoint: ["sh", "-c", "chmod +x /create_queues.sh && docker-entrypoint.sh rabbitmq-server & sleep 10 && /create_queues.sh && tail -f /dev/null"]

  consumerorder:
    build: 
      context: .  # Xây dựng container từ Dockerfile trong thư mục hiện tại
    restart: always
    container_name: consumerorder  # Tên container phải viết thường
    volumes:
      - ./consumerOrder.py:/app/consumerOrder.py  # Mount file script1.py vào container
      - ./log:/app/log # Mount thư mục log từ máy chủ vào container
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1  # Tắt buffer của Python
    command: ["python", "consumerOrder.py"]  # Chạy script1.py
    
  consumerthumbnail:
    build: 
      context: .  # Xây dựng container từ Dockerfile trong thư mục hiện tại
    restart: always
    container_name: consumerthumbnail  # Tên container phải viết thường
    volumes:
      - ./consumerThumbnail.py:/app/consumerThumbnail.py  # Mount file script2.py vào container
      - ./log:/app/log # Mount thư mục log từ máy chủ vào container
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1  # Tắt buffer của Python
    command: ["python", "consumerThumbnail.py"]  # Chạy script2.py
